version: '3'
services:
   db:
    image: postgres:alpine
    env_file:
      - .env
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: db
   api:
    build: .
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      PORT: ${SERVER_PORT}
      DATABASE_URL: 'postgresql://root:Root123@db:5432/KION'
      SECRET: ${SERVER_SECRET}
      FFMPEG: ${SERVER_FFMPEG}
    depends_on:
      - db
    restart:
      on-failure
    container_name: api
volumes:
  db-data:
